# Generated by Django 4.2.1 on 2023-07-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0025_exchangetype_remove_exchanges_exchange_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('id_name', models.CharField(max_length=250, verbose_name='Имя идентификатора')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('ready', models.IntegerField(verbose_name='Количество сделанных акков')),
                ('status', models.CharField(max_length=250, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='manager.products', verbose_name='Номер товара')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар у регистратора',
                'verbose_name_plural': 'Товары у регистраторов',
            },
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250, verbose_name='Статус')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_directions', to='production_management.directions', verbose_name='Отдел')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_prog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инфа регистратора',
                'verbose_name_plural': 'Инфа регистраторов',
            },
        ),
    ]
