# Generated by Django 4.2.1 on 2023-07-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_alter_exchanges_exchange_type'),
        ('production_management', '0002_task_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='manager.products', verbose_name='Номер товара'),
        ),
    ]
