# Generated by Django 4.2.1 on 2023-06-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_emulator_mailtype_typeofnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='emulator',
            field=models.CharField(default=1, max_length=250, verbose_name='Эмулятор'),
            preserve_default=False,
        ),
    ]
