# Generated by Django 4.2.1 on 2023-06-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_products_emulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_pr', to='manager.exchanges', verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='products',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='manager.orders', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='products',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='manager.geo', verbose_name='Гео'),
        ),
    ]
