# Generated by Django 4.2.1 on 2023-06-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_products_exchange_alter_products_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchange_pr', to='manager.exchanges', verbose_name='Биржа'),
        ),
    ]
