# Generated by Django 4.2 on 2023-06-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_emulator_mailtype_typeofnumber_remove_products_geo_and_more'),
        ('manager', '0015_alter_products_exchange'),
    ]

    operations = [
    ]
