# Generated by Django 4.2.1 on 2023-06-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_merge_20230618_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchange_pr', to='manager.exchanges', verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='products',
            name='resident',
            field=models.CharField(max_length=250, verbose_name='Резидент'),
        ),
    ]
