# Generated by Django 4.2.1 on 2023-06-21 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0017_alter_products_exchange_alter_products_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='Срок заказа')),
                ('priority', models.IntegerField(default=3, verbose_name='Приоритет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_save_clients', to='manager.clients')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_save_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненная информация',
                'verbose_name_plural': 'Сохраненная информация',
            },
        ),
    ]
