# Generated by Django 4.2.1 on 2023-06-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_autosave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosave',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_save_clients', to='manager.clients'),
        ),
        migrations.AlterField(
            model_name='autosave',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок заказа'),
        ),
        migrations.AlterField(
            model_name='autosave',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
    ]
