# Generated by Django 4.2.1 on 2023-06-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0020_autosave_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosave',
            name='comment1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='comment2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='comment3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='comment4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='comment5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='emulator1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Эмулятор'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='emulator2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Эмулятор'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='emulator3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Эмулятор'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='emulator4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Эмулятор'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='emulator5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Эмулятор'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='exchange1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autosave_exchange1', to='manager.exchanges', verbose_name='Биржа'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='exchange2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autosave_exchange2', to='manager.exchanges', verbose_name='Биржа'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='exchange3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autosave_exchange3', to='manager.exchanges', verbose_name='Биржа'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='exchange4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autosave_exchange4', to='manager.exchanges', verbose_name='Биржа'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='exchange5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autosave_exchange5', to='manager.exchanges', verbose_name='Биржа'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='geo_id1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Гео'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='geo_id2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Гео'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='geo_id3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Гео'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='geo_id4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Гео'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='geo_id5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Гео'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='mail_type1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип почты'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='mail_type2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип почты'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='mail_type3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип почты'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='mail_type4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип почты'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='mail_type5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип почты'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='price1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='price2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='price3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='price4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='price5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='quantity1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='quantity2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='quantity3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='quantity4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='quantity5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='resident1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Резидент'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='resident2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Резидент'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='resident3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Резидент'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='resident4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Резидент'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='resident5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Резидент'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='type_of_number1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип номера'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='type_of_number2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип номера'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='type_of_number3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип номера'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='type_of_number4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип номера'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='type_of_number5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='autosave',
            name='bundle',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Связка'),
        ),
        migrations.AlterField(
            model_name='autosave',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.clients'),
        ),
        migrations.AlterField(
            model_name='autosave',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
