# Generated by Django 4.2.1 on 2023-06-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_autosave_comment1_autosave_comment2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autosave',
            old_name='mail_type1',
            new_name='mail1',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='mail_type2',
            new_name='mail2',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='mail_type3',
            new_name='mail3',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='mail_type4',
            new_name='mail4',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='mail_type5',
            new_name='mail5',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='type_of_number1',
            new_name='number1',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='type_of_number2',
            new_name='number2',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='type_of_number3',
            new_name='number3',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='type_of_number4',
            new_name='number4',
        ),
        migrations.RenameField(
            model_name='autosave',
            old_name='type_of_number5',
            new_name='number5',
        ),
    ]
