# Generated by Django 4.2.1 on 2023-07-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_exchangetype_remove_exchanges_exchange_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanges',
            old_name='exchange_type',
            new_name='exchange_type',
        ),
    ]
